### ISSUE TITLE
Specify SameSite=None and Secure if the cookie should be sent in cross-site requests.

### ISSUE THREAD

**Issue by VladimirCores** [authorizerdev/docs#16]
Hello Authorizer team.
I'm running Authorizer in Docker on port 8080 and my local development (Vite) on http://localhost:5173/

Trying to authorize with code:
```
   authorizer
      .authorize({
        response_type: 'token',
        response_mode: 'query',
        use_refresh_token: false,
      })
```
![image](https://user-images.githubusercontent.com/442111/192781794-ab51a36c-8858-4f15-8794-4fa6c2165a3f.png)

But have en error:
![image](https://user-images.githubusercontent.com/442111/192781257-6f8b517b-feb1-4556-a947-9356e0009f54.png)

<details>
  <summary>Docker logs:</summary>
`
{"clientIP":"172.19.0.1","dataLength":406,"hostname":"24af85327076","latency":1,"level":"info","method":"POST","msg":"172.19.0.1 - 24af85327076 [28/Sep/2022:12:39:02 +0000] \"POST /graphql\" 200 406 \"http://localhost:8080/app/?state=U3RIblV3V0xuWDJrWTFyTXYxSDNHdkY5VzFSdVc4X01IQWs4LURUWHQwZw==\u0026scope=openid%20profile%20email\u0026redirect_uri=http://localhost:5173\" \"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36\" (1ms)","path":"/graphql","referer":"http://localhost:8080/app/?state=U3RIblV3V0xuWDJrWTFyTXYxSDNHdkY5VzFSdVc4X01IQWs4LURUWHQwZw==\u0026scope=openid%20profile%20email\u0026redirect_uri=http://localhost:5173","statusCode":200,"time":"2022-09-28T12:39:02Z","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"}
{"clientIP":"172.19.0.1","dataLength":26346,"hostname":"24af85327076","latency":1,"level":"info","method":"GET","msg":"172.19.0.1 - 24af85327076 [28/Sep/2022:12:41:18 +0000] \"GET /app/build/chunk-LV6QZLGK.js\" 200 26346 \"http://localhost:8080/app/build/index.js\" \"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36\" (1ms)","path":"/app/build/chunk-LV6QZLGK.js","referer":"http://localhost:8080/app/build/index.js","statusCode":200,"time":"2022-09-28T12:41:18Z","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"}
{"clientIP":"172.19.0.1","dataLength":1611,"hostname":"24af85327076","latency":1,"level":"info","method":"GET","msg":"172.19.0.1 - 24af85327076 [28/Sep/2022:12:41:18 +0000] \"GET /app/build/login-WKTSZ5YU.js\" 200 1611 \"http://localhost:8080/app/?state=WTFseGIxMDAuWVVwSFJwWkVpSGZLcE8zUkFnOXhZMGtZZFVVMUdzSE1KZw==\u0026scope=openid%20profile%20email\u0026redirect_uri=http://localhost:5173\" \"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36\" (1ms)","path":"/app/build/login-WKTSZ5YU.js","referer":"http://localhost:8080/app/?state=WTFseGIxMDAuWVVwSFJwWkVpSGZLcE8zUkFnOXhZMGtZZFVVMUdzSE1KZw==\u0026scope=openid%20profile%20email\u0026redirect_uri=http://localhost:5173","statusCode":200,"time":"2022-09-28T12:41:18Z","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"}
{"clientIP":"172.19.0.1","dataLength":70,"hostname":"24af85327076","latency":1,"level":"info","method":"POST","msg":"172.19.0.1 - 24af85327076 [28/Sep/2022:12:41:18 +0000] \"POST /graphql\" 200 70 \"http://localhost:8080/app/?state=WTFseGIxMDAuWVVwSFJwWkVpSGZLcE8zUkFnOXhZMGtZZFVVMUdzSE1KZw==\u0026scope=openid%20profile%20email\u0026redirect_uri=http://localhost:5173\" \"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36\" (1ms)","path":"/graphql","referer":"http://localhost:8080/app/?state=WTFseGIxMDAuWVVwSFJwWkVpSGZLcE8zUkFnOXhZMGtZZFVVMUdzSE1KZw==\u0026scope=openid%20profile%20email\u0026redirect_uri=http://localhost:5173","statusCode":200,"time":"2022-09-28T12:41:18Z","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"}
{"clientIP":"172.19.0.1","dataLength":128982,"hostname":"24af85327076","latency":1,"level":"info","method":"GET","msg":"172.19.0.1 - 24af85327076 [28/Sep/2022:12:41:18 +0000] \"GET /app/build/chunk-6LKXZIGV.js\" 200 128982 \"http://localhost:8080/app/build/index.js\" \"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36\" (1ms)","path":"/app/build/chunk-6LKXZIGV.js","referer":"http://localhost:8080/app/build/index.js","statusCode":200,"time":"2022-09-28T12:41:18Z","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"}
{"clientIP":"172.19.0.1","dataLength":475,"hostname":"24af85327076","latency":1,"level":"info","method":"GET","msg":"172.19.0.1 - 24af85327076 [28/Sep/2022:12:41:18 +0000] \"GET /app/build/index.css\" 200 475 \"http://localhost:8080/app/?state=WTFseGIxMDAuWVVwSFJwWkVpSGZLcE8zUkFnOXhZMGtZZFVVMUdzSE1KZw==\u0026scope=openid%20profile%20email\u0026redirect_uri=http://localhost:5173\" \"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36\" (1ms)","path":"/app/build/index.css","referer":"http://localhost:8080/app/?state=WTFseGIxMDAuWVVwSFJwWkVpSGZLcE8zUkFnOXhZMGtZZFVVMUdzSE1KZw==\u0026scope=openid%20profile%20email\u0026redirect_uri=http://localhost:5173","statusCode":200,"time":"2022-09-28T12:41:18Z","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"}
{"clientIP":"172.19.0.1","dataLength":406,"hostname":"24af85327076","latency":1,"level":"info","method":"POST","msg":"172.19.0.1 - 24af85327076 [28/Sep/2022:12:41:18 +0000] \"POST /graphql\" 200 406 \"http://localhost:8080/app/?state=WTFseGIxMDAuWVVwSFJwWkVpSGZLcE8zUkFnOXhZMGtZZFVVMUdzSE1KZw==\u0026scope=openid%20profile%20email\u0026redirect_uri=http://localhost:5173\" \"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36\" (1ms)","path":"/graphql","referer":"http://localhost:8080/app/?state=WTFseGIxMDAuWVVwSFJwWkVpSGZLcE8zUkFnOXhZMGtZZFVVMUdzSE1KZw==\u0026scope=openid%20profile%20email\u0026redirect_uri=http://localhost:5173","statusCode":200,"time":"2022-09-28T12:41:18Z","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"}
{"clientIP":"172.19.0.1","dataLength":128540,"hostname":"24af85327076","latency":1,"level":"info","method":"GET","msg":"172.19.0.1 - 24af85327076 [28/Sep/2022:12:41:18 +0000] \"GET /app/build/index.js\" 200 128540 \"http://localhost:8080/app/?state=WTFseGIxMDAuWVVwSFJwWkVpSGZLcE8zUkFnOXhZMGtZZFVVMUdzSE1KZw==\u0026scope=openid%20profile%20email\u0026redirect_uri=http://localhost:5173\" \"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36\" (1ms)","path":"/app/build/index.js","referer":"http://localhost:8080/app/?state=WTFseGIxMDAuWVVwSFJwWkVpSGZLcE8zUkFnOXhZMGtZZFVVMUdzSE1KZw==\u0026scope=openid%20profile%20email\u0026redirect_uri=http://localhost:5173","statusCode":200,"time":"2022-09-28T12:41:18Z","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"}
{"level":"info","msg":"env path: .env","time":"2022-09-28T12:41:06Z"}
{"level":"info","msg":"using OS env instead of .env file","time":"2022-09-28T12:41:06Z"}
{"level":"info","msg":"using in memory store to save sessions","time":"2022-09-28T12:41:06Z"}
{"level":"info","msg":"Starting Authorizer: latest","time":"2022-09-28T12:41:07Z"}
{"level":"info","msg":"Initializing SQL Driver for: sqlite","time":"2022-09-28T12:41:06Z"}
{"level":"info","msg":"Authorizer running at PORT: 8080","time":"2022-09-28T12:41:07Z"}
{"clientIP":"172.19.0.1","dataLength":164,"hostname":"24af85327076","latency":1,"level":"info","method":"GET","msg":"172.19.0.1 - 24af85327076 [28/Sep/2022:12:41:18 +0000] \"GET /authorize\" 302 164 \"http://localhost:5173/\" \"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36\" (1ms)","path":"/authorize","referer":"http://localhost:5173/","statusCode":302,"time":"2022-09-28T12:41:18Z","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"}
{"clientIP":"172.19.0.1","dataLength":1065,"hostname":"24af85327076","latency":1,"level":"info","method":"GET","msg":"172.19.0.1 - 24af85327076 [28/Sep/2022:12:41:18 +0000] \"GET /app/\" 200 1065 \"http://localhost:5173/\" \"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36\" (1ms)","path":"/app/","referer":"http://localhost:5173/","statusCode":200,"time":"2022-09-28T12:41:18Z","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"}
`
</details>

**Any ideas how to overcome the issue?**

**Comment by lakhansamani** [comment]
@VladimirCores I agree,

I will fix it today and allow ability to set via dashboard

**Comment by VladimirCores** [comment]
Trying with `extraHeaders` **is not helping**
![image](https://user-images.githubusercontent.com/442111/192786664-e80f13fc-407d-4a06-bd2e-1a899deadcce.png)

**Comment by lakhansamani** [comment]
That will not help, I am fixing it now

**Comment by lakhansamani** [comment]
@VladimirCores can you update to authorizer 1.1.9 and try it

Thanks

**Comment by VladimirCores** [comment]
The problem gone. But `authorize` method does not return anything from iframe, it just stuck there, and I think that the `message` event does not bubble from window, I put few logs in it and they are never fired:
``` 
iframeEventHandler = function (e: MessageEvent) {
	console.log('[Authorizer -> executeIframe]  iframeEventHandler:', e);
	if (e.origin != eventOrigin) return;
	if (!e.data || !e.data.response) return;

	const eventSource = e.source;

	if (eventSource) {
		(eventSource as any).close();
	}

	console.log(
		'[Authorizer -> executeIframe]  iframeEventHandler:',
		e.data.response,
	);

	e.data.response.error ? rej(e.data.response) : res(e.data.response);

	clearTimeout(timeoutSetTimeoutId);
	window.removeEventListener('message', iframeEventHandler, false);
	setTimeout(removeIframe, CLEANUP_IFRAME_TIMEOUT_IN_SECONDS * 1000);
};

window.addEventListener('message', iframeEventHandler, false);
```

Another question about the iframe - why it contains so much unused tags?
![image](https://user-images.githubusercontent.com/442111/192829456-215b9cf1-8d0a-4533-adf5-8fa82c151d3e.png)

**Comment by lakhansamani** [comment]
@VladimirCores can you share reproducible steps here

Seems you might be using authorizer method incorrectly

**Comment by lakhansamani** [comment]
@VladimirCores here is quick video how I tried it
https://www.loom.com/share/648021fd15844891bf1f661f52ed0840

**Comment by VladimirCores** [comment]
Here is a project: https://drive.google.com/file/d/1Za9sgr1eM7nuIfGDBKr4qXWqXVgp_LPl/view?usp=sharing
(I use `yarn link "@authorizerdev/authorizer-js"` to see changes from the package from another location in my system, project attached to IDEA)

**Comment by lakhansamani** [comment]
@VladimirCores here is the experiment with code you shared. It seems to be working for me
https://www.loom.com/share/56f599ce3964468e99f028ae3d007719

Important change:

```js
await authorizer
        .authorize({
          response_type: 'code',
          use_refresh_token: false,
        })
```

**Comment by VladimirCores** [comment]
Yeah it works for me as well. But ... spent so much time so that already started experimenting with other solutions ...

**Comment by lakhansamani** [comment]
Sorry for that and thanks for the input. Curious to know which solution worked for you. Also on which things we can improve

Thanks

**Comment by VladimirCores** [comment]
@lakhansamani currently trying [zitadel.com](https://zitadel.com/) it was really easy to run, and it has dart SDK, which I needed as well.

**Comment by lakhansamani** [comment]
Thanks
