### ISSUE TITLE
Delete User through AuthRef

### ISSUE THREAD

**Issue by briannezhad** [authorizerdev/docs#40]
It would be great if users could delete their accounts through AuthRef. Because some user may want to close their account and no longer have an account with the application, this feature would be helpful. 

Soft delete would be amazing to have also.

**Comment by lakhansamani** [comment]
@briannezhad this is in progress

**Comment by lakhansamani** [comment]
@briannezhad this is released as part of 1.1.69 & JS SDK 1.2.8
Docs:

https://docs.authorizer.dev/core/graphql-api#deactivate_account
https://docs.authorizer.dev/authorizer-js/functions#--deactivateaccount

**Comment by briannezhad** [comment]
Thank you so much for this feature.
