### ISSUE TITLE
Railway + authorizer - csp blocks requests

### ISSUE THREAD

**Issue by mihaa1** [authorizerdev/docs#47]
I have a newly deployed app, and trying to add authorizer plugin. Works in local - but in production, CSP headers are blocking it.
See photo.
Why does this happen or how can I modify the headers returned from the railway app?
<img width="909" alt="Screenshot 2023-10-18 at 15 20 18" src="https://github.com/authorizerdev/docs/assets/15923264/e570dcdb-51b3-4813-981e-741d39f19736">

**Comment by mihaa1** [comment]
> @mihaa1 can you share the exact version of authorizer you are using?

@authorizerdev/authorizer-js: 1.2.8
@authorizerdev/authorizer-react: 1.1.14

**Comment by lakhansamani** [comment]
@mihaa1 I will also need authorizer version for debugging

**Comment by mihaa1** [comment]
> @mihaa1 I will also need authorizer version for debugging

You mean the cloned repo?
Its says 1.1.70 in railway

**Comment by mihaa1** [comment]
@lakhansamani The problem was on my side, there was some middleware (helmet) in my express server that was adding csp headers.
Sry, and thanks for your response
